// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TSMoreland.ObjectTracker.Data;

#nullable disable

namespace TSMoreland.ObjectTracker.Data.Migrations
{
    [DbContext(typeof(ObjectContext))]
    [Migration("20211203184514_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("TSMoreland.ObjectTracker.Data.Abstractions.Entities.LogEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ObjectEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ObjectEntityId");

                    b.ToTable("LogEntity");
                });

            modelBuilder.Entity("TSMoreland.ObjectTracker.Data.Abstractions.Entities.ObjectEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Objects");
                });

            modelBuilder.Entity("TSMoreland.ObjectTracker.Data.Abstractions.Entities.LogEntity", b =>
                {
                    b.HasOne("TSMoreland.ObjectTracker.Data.Abstractions.Entities.ObjectEntity", null)
                        .WithMany("Logs")
                        .HasForeignKey("ObjectEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TSMoreland.ObjectTracker.Data.Abstractions.Entities.ObjectEntity", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
