// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TSMoreland.ObjectTracker.Data;

#nullable disable

namespace TSMoreland.ObjectTracker.Data.Migrations
{
    [DbContext(typeof(ObjectContext))]
    [Migration("20211208215820_Address")]
    partial class Address
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("TSMoreland.ObjectTracker.Data.Abstractions.Entities.LogEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .IsUnicode(true)
                        .HasColumnType("TEXT");

                    b.Property<int>("ObjectEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Severity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("ObjectEntityId");

                    b.ToTable("LogEntity");
                });

            modelBuilder.Entity("TSMoreland.ObjectTracker.Data.Abstractions.Entities.ObjectEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModified")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<int>("Progress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("Objects");
                });

            modelBuilder.Entity("TSMoreland.ObjectTracker.Data.Abstractions.Entities.LogEntity", b =>
                {
                    b.HasOne("TSMoreland.ObjectTracker.Data.Abstractions.Entities.ObjectEntity", null)
                        .WithMany("Logs")
                        .HasForeignKey("ObjectEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TSMoreland.ObjectTracker.Data.Abstractions.Entities.ObjectEntity", b =>
                {
                    b.OwnsOne("TSMoreland.ObjectTracker.Data.Abstractions.Entities.Address", "Address", b1 =>
                        {
                            b1.Property<int>("ObjectEntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("HouseNumber")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER")
                                .HasDefaultValue(0)
                                .HasColumnName("HouseNumber");

                            b1.Property<string>("PostCode")
                                .IsRequired()
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("TEXT")
                                .HasColumnName("Postcode");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("TEXT")
                                .HasColumnName("Street");

                            b1.HasKey("ObjectEntityId");

                            b1.ToTable("Objects");

                            b1.WithOwner()
                                .HasForeignKey("ObjectEntityId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("TSMoreland.ObjectTracker.Data.Abstractions.Entities.ObjectEntity", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
