// ATLBear.idl : IDL source for ATLBear
//

// This file will be processed by the MIDL tool to
// produce the type library (ATLBear.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

#define GUID_ManagedName 0F21F359-AB84-41E8-9A78-36D110E6D2F9

[
	object,
	uuid(6b42a33c-c7e3-4c64-9081-84174e5c9b97),
	dual,
	nonextensible,
	pointer_default(unique),
    custom(GUID_ManagedName, "Bears.Native.IGrizzly")
]
interface IGrizzly : IDispatch
{
    [id(1), propget] HRESULT Name([out, retval] BSTR* pRetVal);
    [id(1), propput] HRESULT Name([in] BSTR value);
    [id(2)] HRESULT Roar();
	[id(3)] HRESULT Oneify([in] SAFEARRAY(byte) pSource, [out, retval] VARIANT_BOOL *pRetVal);
};

[
	uuid(3cbf3d3a-db02-4a72-8674-8088e52d0ba6),
	version(1.0),
    custom(GUID_ManagedName, "Bears.Native"),
]
library ATLBearLib
{
	importlib("stdole2.tlb");

	[
		uuid(97c0edc5-dd19-4a03-9b21-ba371ebbcc9e),
        custom(GUID_ManagedName, "Bears.Native.Grizzly")
	]
	coclass Grizzly
	{
		[default] interface IGrizzly;
	};
};

import "shobjidl.idl";
