#pragma once

using namespace ATL;

template <class T>
class CProxy_ISimpleOOPObjectEvents : public IConnectionPointImpl<T, &__uuidof( _ISimpleOOPObjectEvents ), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
