// SimpleInProcessCOM.idl : IDL source for SimpleInProcessCOM
//

// This file will be processed by the MIDL tool to
// produce the type library (SimpleInProcessCOM.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";


typedef
[
    uuid(C868E4C5-4139-4961-A643-D8DC28264504),
    version(1.0),
    helpstring("formally defined GUID UDT")
]
struct UDTGuid {

    LONG Data1;
    SHORT Data2;
    SHORT Data3;
    LONGLONG Data4;
} UDTGuid;

[
	object,
	uuid(f2b23b2b-e773-457a-b277-36b21e562fd5),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface ISimpleObject : IDispatch
{
    [id(1), helpstring("Name"), propget]
    HRESULT Name([ out, retval ] BSTR * result);

    [id(2), helpstring("abitrary mutable integer"), propget]
    HRESULT Numeric([ out, retval ] LONG * result);

    [id(2), helpstring("abitrary mutable integer"), propput]
    HRESULT Numeric([in] LONG result);

    [id(3), helpstring("Id"), propget]
    HRESULT Id([ out, retval ] GUID * result);

    [id(4), helpstring("Convert string to lowercase")]
    HRESULT ConvertToString([in] GUID input, [ out, retval ] BSTR * result);
};

[
	uuid(580185ad-317a-4eb7-a6ab-48ebd08c8407),
	version(1.0),
]
library SimpleInProcessCOMLib
{
	importlib("stdole2.tlb");
	[
		uuid(e3d3572d-9e25-4cf3-82f5-45b6f0035a82)
	]
	coclass SimpleObject
	{
		[default] interface ISimpleObject;
	};
};

import "shobjidl.idl";
